### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by szat** [gruossomonica/humanseg_surveillance#1]
Dear fellow scholars, 

I would like to retrain this interesting project but I do not see a link to the dataset. 
On this link http://graphics.unibas.it/www/HumanSegmentation/index.md.html, the dataset is not available. 

Thank you,
Adrian

**Comment by gruossomonica** [comment]
Hi @szat. 
Thanks for the interest!
In **4 Resources** on the [project page](http://graphics.unibas.it/www/HumanSegmentation/index.md.html) is indicated that you have to send an email to request the dataset (red email icon). I'm sorry if it wasn't clear. Please, send an email to monica.gruosso@unibas.it

Best regards,
Monica
